### ISSUE TITLE
start LCD in background or as a service

### ISSUE THREAD

**Issue by rvencu** [alexhorner/WD-DX4000#3]
Hi, I wonder is there a way to start the LCD in the background or as a service at boot? Running it in the foreground is a bit annoying...

**Comment by alexhorner** [comment]
Hey @rvencu 

Apologies for the delay, I have indeed achieved this with a modified service file found at `/usr/lib/systemd/system/LCDd.service`. Here is how I have it set up:

```
[Unit]
Description=LCD display daemon
Documentation=man:LCDd(8) http://www.lcdproc.org/

[Service]
User=root
ExecStartPre=bash -c "echo \"255\" > /sys/class/hwmon/hwmon1/pwm3"
ExecStart=/usr/sbin/LCDd -s 1 -f -c /etc/LCDd.conf
ExecStartPost=bash -c "sleep 5 && lcdproc C P M U S K"
ExecStop=bash -c "echo \"128\" > /sys/class/hwmon/hwmon1/pwm3"

[Install]
WantedBy=multi-user.target
```

This will bring the LCD brightness to 100% and then start `lcdproc` with a slight delay of 5 seconds in order to allow `LCDd` to fully start.

When the service is stopped, `LCDd` stops which in turn kills `lcdproc`. In addition, it also sets the LCD brightness to 50% which is approx the default after boot.

Please see the `lcdproc` help menu for info on what `lcdproc C P M U S K` means, as the characters represent the rotating screens I have selected for display on my system

**Comment by rvencu** [comment]
Great !

**Comment by blairjj** [comment]
FYI if you are running Debian 11, you will need to make sure that you use: 'apt-get install lcdproc lcdproc-extra-drivers' to ensure that you have the extra drivers for hd44780
